### ISSUE TITLE
[coverage]: TypeError: Cannot read property 'text' of undefined?

### ISSUE THREAD

**Issue by surfjedi** [textioHQ/karma-istanbul-preprocessor#1]
Hi,

I was having the errors you described this fixes, and they went away but i have another.

I'm trying to get coverage with a webpack angular project.

Here is the error:
 TypeError: Cannot read property 'text' of undefined
  at /Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/report/html.js:288:53
  at Array.forEach (native)
  at annotateBranches (/Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/report/html.js:255:30)
  at HtmlReport.Report.mix.writeDetailPage (/Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/report/html.js:426:9)
  at /Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/report/html.js:489:26
  at SyncFileWriter.extend.writeFile (/Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/util/file-writer.js:57:9)
  at FileWriter.extend.writeFile (/Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/util/file-writer.js:147:23)
  at /Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/report/html.js:488:24
  at Array.forEach (native)
  at HtmlReport.Report.mix.writeFiles (/Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/report/html.js:482:23)
  at /Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/report/html.js:484:22
  at Array.forEach (native)
  at HtmlReport.Report.mix.writeFiles (/Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/report/html.js:482:23)
  at HtmlReport.Report.mix.writeReport (/Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/report/html.js:566:14)
  at LcovReport.Report.mix.writeReport (/Users/i0355/WebstormProjects/provisioner/node_modules/istanbul/lib/report/lcov.js:55:19)
  at writeReport (/Users/i0355/WebstormProjects/provisioner/node_modules/karma-coverage/lib/reporter.js:68:16)
  at /Users/i0355/WebstormProjects/provisioner/node_modules/karma-coverage/lib/reporter.js:296:11
  at /Users/i0355/WebstormProjects/provisioner/node_modules/karma/lib/helper.js:144:7
  at /Users/i0355/WebstormProjects/provisioner/node_modules/graceful-fs/polyfills.js:279:18
  at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by surfjedi** [comment]
here is my karma.conf
`// Reference: http://karma-runner.github.io/0.12/config/configuration-file.html

let webpackConfig = require('./webpack.config');
webpackConfig.devtool = 'inline-source-map';
webpackConfig.entry = {};
process.env.BABEL_ENV = 'test';
module.exports = function karmaConfig (config) {
    config.set({
        frameworks:
            ['mocha', 'chai', 'sinon', 'chai-sinon'],


        reporters: [
            // Reference: https://github.com/mlex/karma-spec-reporter
            // Set reporter to print detailed results to console
            'progress',

            // Reference: https://github.com/karma-runner/karma-coverage
            // Output code coverage files
            'coverage'
        ],
        client: {
          captureConsole: true
        },
        files: [

            /* MOCHA */
            './src/test/lib/specHelper.js',
            './src/test/lib/mockData.js',
            // Grab all files in the app folder that contain .spec.
            'src/tests.webpack.js',
        ],
        // list of files to exclude
        exclude: [
            // Excluding midway tests for now; comment this line out when you want to run them
            './src/test/midway/**/*.spec.js',
            './src/test/specs/dashboard-route.spec.js',
        ],
        preprocessors: {
            // Reference: http://webpack.github.io/docs/testing.html
            // Reference: https://github.com/webpack/karma-webpack
            // Convert files with webpack and load sourcemaps
            // 'src/tests.webpack.js': ['webpack', 'sourcemap', 'coverage']
            'src/tests.webpack.js': ['webpack','istanbul']
        },

        browsers: [
            // Run tests using PhantomJS
            'PhantomJS', 'Chrome'
        ],

        singleRun: true,

        // Configure code coverage reporter
        coverageReporter: {
            dir: 'coverage/',
            reporters: [
                {type: 'text-summary'},
                {type: 'html'},
                {type: 'lcov'},
                {type: 'json'}
            ]
        },

        webpack: require('./webpack.config'),

        // Hide webpack build information from output
        webpackMiddleware: {
            noInfo: 'errors-only'
        }
    });
};
`

**Comment by surfjedi** [comment]
and my webpack file:

`var path = require('path'),
    webpack = require('webpack'),
    libPath = path.join(__dirname, 'src'),
    wwwPath = path.join(__dirname, 'www'),

// pkg = require('./package.json'),
    CopyWebpackPlugin = require('copy-webpack-plugin'),
    HtmlWebpackPlugin = require('html-webpack-plugin'),
    os = require('os');

/**
 * Env
 * Get npm lifecycle event to identify the environment
 */
// var ENV = process.env.npm_lifecycle_event;
let ENV = process.env.npm_lifecycle_event || process.env.NODE_ENV ;
let isTest = ENV === 'test' || ENV === 'test-watch';
let isDev = ENV === 'dev' || ENV === 'dev-remote';
let isProd = ENV === 'build';

console.log('ENV:', ENV);
console.log('isTest:', isTest);
console.log('process.env.npm_lifecycle_event :', process.env.npm_lifecycle_event );
console.log('process.env.NODE_ENV:', process.env.NODE_ENV);

module.exports = function makeWebpackConfig () {
    /**
     * Config
     * Reference: http://webpack.github.io/docs/configuration.html
     * This is the object where all configuration gets set
     */
    var config = {};
    config.context = path.join(libPath),

        /**
     * Entry
     * Reference: http://webpack.github.io/docs/configuration.html#entry
     * Should be an empty object if it's generating a test build
     * Karma will set this when it's a test build
     */
    config.entry = isTest ? {} : {
        app: path.join(libPath, 'app/app.module.js'),
        vendor: [
            'jquery',
            'angular',
            'angular-animate',
            'angular-resource',
            'angular-route',
            'angular-sanitize',
            'angular-aria',
            'angular-material',
            'angular-material-data-table',
            'angular-socket-io',
            'c3',
            'd3',
            'toastr',
            'moment'
        ]
    };

    /**
     * Output
     * Reference: http://webpack.github.io/docs/configuration.html#output
     * Should be an empty object if it's generating a test build
     * Karma will handle setting it up for you when it's a test build
     */
    config.output = isTest ? {} : {
        // Absolute output directory
        path: path.join(wwwPath),
        // filename: 'bundle.js'
        filename: 'bundle-[hash:6].js'
    };

    /**
     * Devtool
     * Reference: http://webpack.github.io/docs/configuration.html#devtool
     * Type of sourcemap to use per build type
     */
    if (isTest) {
        config.devtool = 'inline-source-map';
    } else if (isProd) {
        config.devtool = 'source-map';
    } else {
        config.devtool = 'source-map';
    }

    /**
     * Loaders
     * Reference: http://webpack.github.io/docs/configuration.html#module-loaders
     * List: http://webpack.github.io/docs/list-of-loaders.html
     * This handles most of the magic responsible for converting modules
     */

    // Initialize module
    config.module = {
        preLoaders: [],
        loaders: [
            //run all js thru babel
            {
                test: /\.js$/,
                loader: 'babel',
                exclude: /node_modules/,
                query: {
                    presets: ['es2015'],
                    env: {
                      'test': {
                        'plugins': [
                          ['__coverage__', {'ignore':'*.+(spec|webpack).*'}]
                        ]
                      }
                    }
                }
            },
            //load all css into a js bundle which you can require
            {
                test: /\.css$/,
                loader: 'style!css',
                exclude: /node_modules/
            },
            //run all sass thru loader, then css loader, then into js bundle
            {
                test: /\.scss$/,
                loader: 'style!css!sass',
                exclude: /node_modules/
            },
            //load images thru loader and either produce data url or url https://github.com/webpack/url-loader
            {
                test: /\.(eot|woff|woff2|ttf|svg|png|jpg)$/,
                loader: 'url-loader?limit=25000&name=[name].[ext]',
                exclude: /node_modules/
            },
            // https://github.com/webpack/raw-loader
            {
                test: /\.html$/,
                loader: 'raw',
                exclude: /node_modules/
            },
            {
                test: /\.jade$/,
                loader: 'pug-loader',
                exclude: /node_modules/
            }
        ]
    };

    // ISPARTA LOADER
    // Reference: https://github.com/ColCh/isparta-instrumenter-loader
    // Instrument JS files with Isparta for subsequent code coverage reporting
    // Skips node_modules and files that end with .test.js
    // if (isTest) {
    //     config.module.preLoaders.push({
    //         test: /\.js$/,
    //         exclude: [
    //             /node_modules/,
    //             /\.spec\.js$/,
    //             /\.webpack\.js$/
    //         ],
    //         loader: 'isparta-loader'
    //     })
    // }


    /**
     * Plugins
     * Reference: http://webpack.github.io/docs/configuration.html#plugins
     * List: http://webpack.github.io/docs/list-of-plugins.html
     */
    config.plugins = [

        //try to cut down loading all locale from moment
        new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
        //custom plugin to build module or not
        new webpack.DefinePlugin({
            ON_DEV: process.env.NODE_ENV === 'dev'
        }),
        new webpack.DefinePlugin({
            ON_TEST: process.env.NODE_ENV === 'test'
        }),
        //just copied for now since we don't need hasing or anything for now
        // HtmlWebpackPlugin: Simplifies creation of HTML files to serve your webpack bundles :
        // https://www.npmjs.com/package/html-webpack-plugin
        new HtmlWebpackPlugin({
            template: 'index.jade',
            hash: false,
            title: 'title',
            test: ENV === 'protractor' ? true :false
        }),
        // OccurenceOrderPlugin: Assign the module and chunk ids by occurrence count. :
        // https://webpack.github.io/docs/list-of-plugins.html#occurenceorderplugin
        // new webpack.optimize.OccurenceOrderPlugin(),
        //
        // new webpack.optimize.UglifyJsPlugin({
        //     mangle: false
        // }),
        new CopyWebpackPlugin([
            { from: './content', to: './content' },
            { from: 'app/**/*.html' },
            {from: '../node_modules/socket.io-client/socket.io.js', to: './vendor/socket.io.js'}
        ])
    ];

    // Skip rendering index.html in test mode
    if (!isTest) {
        // Reference: https://github.com/ampedandwired/html-webpack-plugin
        // Render index.html
        config.plugins.push(
            new webpack.optimize.CommonsChunkPlugin({
                name: 'vendor',
                filename: 'vendor.bundle.js'
            })
        );
    }

    // Add build specific plugins when not 'dev'
    if (isProd) {
        config.plugins.push(
            // Reference: http://webpack.github.io/docs/list-of-plugins.html#noerrorsplugin
            // Only emit files when there are no errors
            new webpack.NoErrorsPlugin(),

            // Reference: http://webpack.github.io/docs/list-of-plugins.html#dedupeplugin
            // Dedupe modules in the output
            new webpack.optimize.DedupePlugin(),

            // Reference: http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin
            // Minify all javascript, switch loaders to minimizing mode
            new webpack.optimize.UglifyJsPlugin({
                mangle: false
            })
        );
    }

    /**
     * Dev server configuration
     * Reference: http://webpack.github.io/docs/configuration.html#devserver
     * Reference: http://webpack.github.io/docs/webpack-dev-server.html
     */
    config.devServer = {
        stats: 'minimal',
        historyApiFallback: true,
        inline: true,
        host: os.hostname()+'.den.ofi.com',
        proxy: {
            '/api': {
                target: 'http://localhost:3000',
                secure: false
            },
            '/sso': {
                target: 'http://localhost:3000',
                secure: false
            },
            '/health': {
                target: 'http://localhost:3000',
                secure: false
            }
        }
    };

    return config;
}();
`

**Comment by AnilRedshift** [comment]
Hi,

Can you just use `karma-coverage`? What is your scenario for needing `istanbul` as a standalone package?

**Comment by bkolba** [comment]
Closing issue due to inactivity and sounds like fundamentally different configs. If there's a fix + PR for us to look at we will re-evaluate.
